global:
  scrape_interval: 30s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - localhost:9100

  - job_name: services
    static_configs:
      - targets:
          - localhost:3000
          - localhost:3001
          - localhost:3002
